
apiVersion: v1 
kind: Service 
metadata:
  name: escback-service 

spec: 
  type: NodePort 
  ports:
  - port: 8008 
    targetPort: 10001 
    protocol: TCP 
    nodePort: 30003 
  selector:
    app: escback01 
