apiVersion: v1 
kind: Service 
metadata:
  name: esc-prometheus-service

spec: 
  type: NodePort 
  ports:
  - port: 9009 
    targetPort: 9090 
    protocol: TCP 
    nodePort: 30005 
  selector:
    app: prometheus 
